sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t bahar444/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bahar444/react-test npm test

after_success:
  - docker build -t bahar444/multi-client ./client
  - docker build -t bahar444/multi-nginx ./nginx
  - docker build -t bahar444/multi-server ./server
  - docker build -t bahar444/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bahar444/multi-client
  - docker push bahar444/multi-nginx
  - docker push bahar444/multi-server
  - docker push bahar444/multi-worker
